// Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package shared

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"gopkg.in/yaml.v3"

	"github.com/NVIDIA/eidos/pkg/errors"
	"github.com/NVIDIA/eidos/pkg/recipe"
)

// IsSafePathComponent returns true if name is a single path component without
// any separators or parent directory references.
func IsSafePathComponent(name string) bool {
	if name == "" {
		return false
	}
	if strings.Contains(name, "/") || strings.Contains(name, "\\") {
		return false
	}
	if strings.Contains(name, "..") {
		return false
	}
	return true
}

// SafeJoin joins baseDir and name, then verifies the result is contained
// within baseDir. This prevents path traversal when name comes from
// untrusted input (e.g., component names from recipe data).
func SafeJoin(baseDir, name string) (string, error) {
	if filepath.IsAbs(name) {
		return "", errors.New(errors.ErrCodeInvalidRequest,
			fmt.Sprintf("path component %q is absolute and escapes base directory", name))
	}
	absBase, err := filepath.Abs(baseDir)
	if err != nil {
		return "", errors.Wrap(errors.ErrCodeInternal, "failed to resolve base directory", err)
	}
	joined := filepath.Clean(filepath.Join(absBase, name))
	if joined != absBase && !strings.HasPrefix(joined, absBase+string(filepath.Separator)) {
		return "", errors.New(errors.ErrCodeInvalidRequest,
			fmt.Sprintf("path component %q escapes base directory", name))
	}
	return joined, nil
}

// WriteValuesFile writes a values.yaml file with header comment to baseDir/filename.
// It uses SafeJoin to verify the output path stays within baseDir.
func WriteValuesFile(values map[string]any, baseDir, filename string) (string, int64, error) {
	outputPath, err := SafeJoin(baseDir, filename)
	if err != nil {
		return "", 0, err
	}

	var buf strings.Builder
	buf.WriteString("# Generated by Cloud Native Stack\n")
	buf.WriteString("---\n")

	if len(values) > 0 {
		yamlBytes, err := yaml.Marshal(values)
		if err != nil {
			return "", 0, errors.Wrap(errors.ErrCodeInternal, "failed to marshal values", err)
		}
		buf.Write(yamlBytes)
	}

	content := buf.String()
	if err := os.WriteFile(outputPath, []byte(content), 0600); err != nil {
		return "", 0, errors.Wrap(errors.ErrCodeInternal, "failed to write values file", err)
	}

	return outputPath, int64(len(content)), nil
}

// GenerateFromTemplate renders a template and writes it to baseDir/filename.
// It uses SafeJoin to verify the output path stays within baseDir.
func GenerateFromTemplate(tmplContent string, data any, baseDir, filename string) (string, int64, error) {
	outputPath, err := SafeJoin(baseDir, filename)
	if err != nil {
		return "", 0, err
	}

	tmpl, err := template.New("template").Parse(tmplContent)
	if err != nil {
		return "", 0, errors.Wrap(errors.ErrCodeInternal, "failed to parse template", err)
	}

	var buf strings.Builder
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", 0, errors.Wrap(errors.ErrCodeInternal, "failed to execute template", err)
	}

	content := buf.String()
	if err := os.WriteFile(outputPath, []byte(content), 0600); err != nil {
		return "", 0, errors.Wrap(errors.ErrCodeInternal, "failed to write file", err)
	}

	return outputPath, int64(len(content)), nil
}

// NormalizeVersion removes the 'v' prefix from a version string.
// It returns the input unchanged if no prefix is present.
func NormalizeVersion(v string) string {
	return strings.TrimPrefix(v, "v")
}

// NormalizeVersionWithDefault removes the 'v' prefix and defaults empty
// strings to "0.1.0". Use this for Helm chart metadata where a version
// is always required.
func NormalizeVersionWithDefault(v string) string {
	v = strings.TrimPrefix(v, "v")
	if v == "" {
		return "0.1.0"
	}
	return v
}

// SortComponentRefsByDeploymentOrder sorts component refs by deployment order.
// Components in the order list are sorted by their position; components not in
// the order list are placed after ordered components and sorted alphabetically.
func SortComponentRefsByDeploymentOrder(refs []recipe.ComponentRef, order []string) []recipe.ComponentRef {
	if len(order) == 0 {
		return refs
	}

	orderMap := make(map[string]int, len(order))
	for i, name := range order {
		orderMap[name] = i
	}

	sorted := make([]recipe.ComponentRef, len(refs))
	copy(sorted, refs)

	sort.SliceStable(sorted, func(i, j int) bool {
		orderI, okI := orderMap[sorted[i].Name]
		orderJ, okJ := orderMap[sorted[j].Name]

		if !okI && !okJ {
			return sorted[i].Name < sorted[j].Name
		}
		if !okI {
			return false
		}
		if !okJ {
			return true
		}
		return orderI < orderJ
	})

	return sorted
}

// SortComponentNamesByDeploymentOrder sorts component name strings according
// to deployment order. Components in the order list are sorted by their
// position; components not in the order list are placed after ordered
// components and sorted alphabetically.
func SortComponentNamesByDeploymentOrder(components []string, deploymentOrder []string) []string {
	orderMap := make(map[string]int)
	for i, name := range deploymentOrder {
		orderMap[name] = i
	}

	sorted := make([]string, len(components))
	copy(sorted, components)

	sort.Slice(sorted, func(i, j int) bool {
		orderI, okI := orderMap[sorted[i]]
		orderJ, okJ := orderMap[sorted[j]]
		if okI && okJ {
			return orderI < orderJ
		}
		if okI {
			return true
		}
		if okJ {
			return false
		}
		return sorted[i] < sorted[j]
	})

	return sorted
}
